name: ci/build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Linting
        run: yarn run lint

      - name: Build
        run: yarn run build
